### ISSUE TITLE
Wrapped Creaper management client does not survive reload

### ISSUE THREAD

**Issue by mnovak1** [jboss-eap-qe/eap-microprofile-test-suite#169]
There is intermittent issue with wrapped `OnlineManagementClient`:
```
@Override
public void setup(ManagementClient managementClient, String s) throws Exception {
    new Administration(ManagementClientProvider.onlineStandalone(managementClient)).reload();
}        
```
that sometimes it does not survive reload of WF/EAP server [1] and exception:
```
java.lang.UnsupportedOperationException: Can't reconnect a wrapped client
	at org.wildfly.extras.creaper.core.online.OnlineManagementClientImpl.reconnect(OnlineManagementClientImpl.java:221)
	at org.wildfly.extras.creaper.core.online.LazyOnlineManagementClient.reconnect(LazyOnlineManagementClient.java:91)
	at org.wildfly.extras.creaper.core.online.operations.admin.StandaloneAdministrationOperations.waitUntilServerIsRunning(StandaloneAdministrationOperations.java:106)
	at org.wildfly.extras.creaper.core.online.operations.admin.StandaloneAdministrationOperations.performRestartOperation(StandaloneAdministrationOperations.java:93)
	at org.wildfly.extras.creaper.core.online.operations.admin.StandaloneAdministrationOperations.reload(StandaloneAdministrationOperations.java:32)
	at org.wildfly.extras.creaper.core.online.operations.admin.Administration.reload(Administration.java:60)
	at org.jboss.eap.qe.microprofile.health.integration.FailSafeCDIHealthBaseTest.before(FailSafeCDIHealthBaseTest.java:57)
```
is thrown. Creaper is doing regular "health" checks of connection and in case it fails it starts reconnect procedure which is not supported with wrapped management client.

How to resolve situation:
`ManagementClientProvider.onlineStandalone(Management managementClient)` method should be deprecated and removed. Existing occurrences should be re-factored to use other `ManagementClientProvider` methods (without wrapping `ManagementClient`).

`ServerSetupTask` API is passing `managementClient` as parameter in setup() and tearDown() methods. So ignoring those parameters is breaking its purpose. To make it more clear there is suggestion to extend ServerSetupTask like:
```
public interface MicroProfileServerSetupTask extends ServerSetupTask {
    @Override
    default public void setup(ManagementClient managementClient, String containerId) throws Exception {
        setup();
    }

   public void setup() throws Exception;

    @Override
    default public void tearDown(ManagementClient managementClient, String containerId) throws Exception {
        tearDown();
    }

    public void tearDown() throws Exception;
}
```
and use `MicroProfileServerSetupTask` interface so there is used `ServerSetupTask` lifecycle but API breakage is hidden. If this is not clean enough then we can create our own Arquillian extension.

[1] https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/eap-7.x-microprofile-testsuite/jdk=oracle-java-11,label_exp=RHEL7/lastCompletedBuild/testReport/junit/org.jboss.eap.qe.microprofile.health.integration/FailSafeCDICustomConfigSourceProviderHealthTest/testReadinessEndpointUp/

**Comment by fabiobrz** [comment]
Thanks @mnovak1. IMO The solution that you are suggesting seems good enough to support the goal at the moment, given that would make use of the Arquillian lifecycle management for server configuration and at the same time would hide the mismatch. It seems also that it can be adopted quickly, although leaving the chance to end up with an extension - if that's really needed - later on. WDYT?

**Comment by mnovak1** [comment]
@fabiobrz yes, once it's switched into `MicroProfileServerSetupTask` interface, moving to extension would be very simple (there would be no changes to tests).

**Comment by fabiobrz** [comment]
Filed #173 to introduce the interface. I'll file one for adoption in MP OpenAPI spec soon after this one gets merged.
