### ISSUE TITLE
Add fail-fast mechanism for starting docker containers

### ISSUE THREAD

**Issue by mnovak1** [jboss-eap-qe/eap-microprofile-test-suite#28]
In case that docker container is started with bad/malformed parameters command - for example there is bad name/version of docker image, starting of docker container must fail fast and does not wait for `containerReadyTimeout` for exception to be thrown.

**Comment by rsvoboda** [comment]
```
wildfly> Unable to find image 'jboss/wildfly:18.0.0.00' locally
wildfly> docker: Error response from daemon: manifest for jboss/wildfly:18.0.0.00 not found.
wildfly> See 'docker run --help'.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 60.072 s <<< FAILURE! - in org.jboss.eap.qe.ts.common.docker.DockerTest
[ERROR] org.jboss.eap.qe.ts.common.docker.DockerTest  Time elapsed: 60.072 s  <<< ERROR!
java.lang.Exception: Container was not ready in timeout : 60000 ms
	at org.jboss.eap.qe.ts.common.docker.ContainerReadyCondition.waitUntilReady(ContainerReadyCondition.java:17)
	at org.jboss.eap.qe.ts.common.docker.Docker.start(Docker.java:80)
	at org.jboss.eap.qe.ts.common.docker.Docker.before(Docker.java:103)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```
