### ISSUE TITLE
JWT tests are failing regularly with "org.glassfish.json.JsonProviderImpl"

### ISSUE THREAD

**Issue by fabiobrz** [jboss-eap-qe/eap-microprofile-test-suite#282]
Running the TS against WildFly, we spotted the following traces for most of the MP JWT tests, [when building claims](https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/tooling-mp-jwt-auth-tool/src/main/java/org/jboss/eap/qe/microprofile/jwt/auth/tool/JwtClaims.java#L40).

```
jakarta.json.JsonException: Provider org.eclipse.parsson.JsonProviderImpl not found
	at jakarta.json.spi.JsonProvider.provider(JsonProvider.java:124)
	at jakarta.json.Json.createObjectBuilder(Json.java:278)
	at org.jboss.eap.qe.microprofile.jwt.auth.tool.JwtClaims.toJson(JwtClaims.java:40)
	at org.jboss.eap.qe.microprofile.jwt.auth.tool.JsonWebToken.<init>(JsonWebToken.java:18)
	at org.jboss.eap.qe.microprofile.jwt.auth.tool.JsonWebToken$Builder.build(JsonWebToken.java:146)
	at org.jboss.eap.qe.microprofile.jwt.auth.tool.JwtHelper.generateProperSignedJwt(JwtHelper.java:92)
	at org.jboss.eap.qe.microprofile.jwt.auth.tool.JwtHelper.generateProperSignedJwt(JwtHelper.java:46)
	at org.jboss.eap.qe.microprofile.jwt.auth.tool.JwtHelper.generateProperSignedJwt(JwtHelper.java:35)
	at org.jboss.eap.qe.microprofile.jwt.activation.AnnotationActivationCompatibilityTest.testSameTokenReceived(AnnotationActivationCompatibilityTest.java:72)
	...
```

This started to pop up lately, although the dependency version didn't change in a while.

**Comment by jbliznak** [comment]
This is caused by https://github.com/jboss-eap-qe/eap-microprofile-test-suite/pull/279, in particular the problematic update WildFly Core from 19.0.0.Beta15 to 23.0.1.Final

I quickly tried different versions and findings are as follows:
23.0.0.Beta5 version is still working
23.0.0.Final and newer are causing tests to fail

diff https://github.com/wildfly/wildfly-core/compare/23.0.0.Beta5...23.0.0.Final
The most likely candidate for breaking change is https://issues.redhat.com/browse/WFCORE-6656

diff in dependency tree is `[INFO] |  |  \- org.eclipse.parsson:parsson:jar:1.1.5:test` missing in 23.0.0.Final+
so that leads me to probable solution https://issues.redhat.com/browse/WFLY-18897

**Comment by fabiobrz** [comment]
> This is caused by #279, in particular the problematic update WildFly Core from 19.0.0.Beta15 to 23.0.1.Final
> 
> I quickly tried different versions and findings are as follows: 23.0.0.Beta5 version is still working 23.0.0.Final and newer are causing tests to fail
> 
> diff [wildfly/wildfly-core@23.0.0.Beta5...23.0.0.Final](https://github.com/wildfly/wildfly-core/compare/23.0.0.Beta5...23.0.0.Final) The most likely candidate for breaking change is https://issues.redhat.com/browse/WFCORE-6656
> 
> diff in dependency tree is `[INFO] | | \- org.eclipse.parsson:parsson:jar:1.1.5:test` missing in 23.0.0.Final+ so that leads me to probable solution https://issues.redhat.com/browse/WFLY-18897

Thanks @jbliznak - I do agree with you, after spending some time on rebuilding the dependency tree at various points and trying to find where that `parsson` dependency was dropped. That being said I didn't get so far yet, so I'll verify your hints and keep you posted. Thanks for now!
